---
title: "Data Scraping and Cleaning"
output: html_document
date: "2024-10-16"
---

```{r}
library(dplyr)
library(jsonlite)
library(curl)
library(RCurl)
library(tidyr)
library(data.table)
library(httr)
library(RcppSimdJson)
library(rbenchmark)
library(furrr)
library(future)
library(purrr)
library(parallel)
library(rlang)
library(progress)
library(vroom)
```

```{r}
hdb_url <- "https://api.data.gov.sg/v1/transport/carpark-availability"
test_date <- as.POSIXct("2023-05-06 00:01:00")
test_date_char <- as.character(test_date)
weather_url <- "https://api-open.data.gov.sg/v2/real-time/api/twenty-four-hr-forecast"
tmp_url <- "https://api.data.gov.sg/v1/environment/air-temperature"
rf_url <- "https://api-open.data.gov.sg/v2/real-time/api/rainfall"
humid_url <- "https://api.data.gov.sg/v1/environment/relative-humidity"
ws_url <- "https://api.data.gov.sg/v1/environment/wind-speed"

data_gov_generic_url <- "https://data.gov.sg/api/action/datastore_search?resource_id="
dm_carpark_url <- "https://datamall2.mytransport.sg/ltaodataservice/CarParkAvailabilityv2"
rf2_url <- "https://api.data.gov.sg/v1/environment/rainfall"
```

```{r}
#Initializing Parallel R Sessions
n_cores <- availableCores() - 1
plan(multisession, workers = n_cores)

pb <- progress_bar$new(
    total = 100,
    format = "  downloading [:bar] :percent eta: :eta",
    width = 60
)
```

Code test for retreiving carpark data
```{r}
# test_date_char <- as.character(test_date)
# 
# url_test <- paste0(hdb_url, "?date_time=",
#               substr(test_date_char, 1, 10), "T",
#               substr(test_date_char, 12, 19))
# 
# raw_data_test <- GET(url_test)
# data_test <- RcppSimdJson::fparse(raw_data_test$content)
# 
# is.data.frame(data_test$items$carpark_data[[1]])
# 
# carpark_test <- setDT(data_test$items$carpark_data[[1]])
# 
# carpark_test$total_lots <- sapply(carpark_test$carpark_info, `[[`, 1)
# carpark_test$lot_type <- sapply(carpark_test$carpark_info, `[[`, 2)
# carpark_test$lots_available <- sapply(carpark_test$carpark_info, `[[`, 3)
# 
# carpark_test$datetime <- rep(test_date, nrow(carpark_test))
# 
# carpark_test <- carpark_test %>%
#   unnest(cols = c(total_lots, lot_type, lots_available)) %>%
#   select(-carpark_info, -update_datetime)
# 
# carpark_test <- setDT(carpark_test)
# 
# object.size(carpark_test)
# 
# is.data.table(carpark_test)
```

```{r}
get_rainfall_data_hour <- function(datetime, url){
  dt_char <- as.character(datetime)
  url <- paste0(url, "?date_time=", 
                substr(dt_char, 1, 10), "T", 
                substr(dt_char, 12, 19))
  response <- GET(url)
  
  if (status_code(response) != 200) {
    stop("Error")
  }

  data <- response$content
  json_data <- RcppSimdJson::fparse(data)
  
  if(!("items" %in% names(json_data) && length(json_data$items) > 0)) {
    stop("Error")
  }
  
  rf <- json_data$items$readings[[1]]
  rf_st <- json_data$metadat$stations[,c(1, 4)]
  rf_st$Longtitude <- sapply(rf_st$location, `[[`, 2)
  rf_st$Latitude <- sapply(rf_st$location, `[[`, 1)
  rf_st <- rf_st %>% select(-location)
  rf_final <- merge(rf_st, rf, by.x = "id", by.y = 'station_id')
  rf_final$datetime <- rep(datetime, nrow(rf_final))
  return(setDT(rf_final))
}
```

```{r}
retrieve_carpark_info <- function(url){
  carpark_data <- RcppSimdJson::fparse(GET(url)$content)
  carpark_info_data <- carpark_data$result$records
  return(setDT(carpark_info_data))
}

carpark_info_id <- "d_23f946fa557947f93a8043bbef41dd09"
carpark_data_url <- paste0(data_gov_generic_url, carpark_info_id)
carpark_nrows <- RcppSimdJson::fparse(GET(carpark_data_url)$content)$result$total

offset_num <- seq(100, carpark_nrows, 100)
offset_url <- paste0(rep(carpark_data_url, length(offset_num)),
                     rep('&offset=', length(offset_num)), 
                     as.character(offset_num))
```

```{r}
#wind speed extraction
wind_extract_data <- function(datetime, url){
  dt_char <- as.character(datetime)
  ws_url_test <- paste0(ws_url, "?date_time=", 
                   substr(dt_char, 1, 10), "T", 
                   substr(dt_char, 12, 19))
  ws_data <- RcppSimdJson::fparse(GET(ws_url_test)$content)
  ws_st <- ws_data$metadata$stations
  ws_st$latitude <- sapply(ws_st$location, `[[`, 1)
  ws_st$longtitude <- sapply(ws_st$location, `[[`, 2)
  ws_st <- ws_st %>% select(c(-device_id, -location))
  ws_rf <- ws_data$items$readings[[1]]
  ws_final <- merge(ws_st, ws_rf, by.x = 'id', by.y = 'station_id')
  ws_final$datetime <- rep(datetime, nrow(ws_final))
  return(setDT(ws_final))
}
```

```{r}
#humidity extraction function
humidity_extract_data <- function(datetime, url){
  dt_char <- as.character(datetime)
  hm_url <- paste0(url, "?date_time=", 
                     substr(dt_char, 1, 10), "T", 
                     substr(dt_char, 12, 19))
  hm_data <- RcppSimdJson::fparse(GET(hm_url)$content)
  hm_st <- hm_data$metadata$stations
  hm_st$latitude <- sapply(hm_st$location, `[[`, 1)
  hm_st$longtitude <- sapply(hm_st$location, `[[`, 2)
  hm_st <- hm_st %>% select(c(-device_id, -location))
  hm_rd <- hm_data$items$readings[[1]]
  hm_final <- merge(hm_st, hm_rd, by.x = 'id', by.y = 'station_id')
  hm_final$datetime <- rep(datetime, nrow(hm_final))
  return(setDT(hm_final))
}
```

```{r}
#rainfall extraction function
rf_extract_data <- function(datetime, url){
  dt_char <- as.character(datetime)
  rf_url <- paste0(url, "?date_time=", 
                   substr(dt_char, 1, 10), "T", 
                   substr(dt_char, 12, 19))

  rf_data <- RcppSimdJson::fparse(GET(rf_url)$content)
  rf_st <- rf_data$data$stations
  rf_st$latitude <- sapply(rf_st$location, `[[`, 1)
  rf_st$longtitude <- sapply(rf_st$location, `[[`, 2)
  rf_st <- rf_st %>% select(c(-deviceId, -location))
  rf_rd <- rf_data$data$readings$data[[1]]
  rf_final <- merge(rf_st, rf_rd, by.x = 'id', by.y = 'stationId')
  rf_final$datetime <- rep(datetime, nrow(rf_final))
  return(rf_final)
}
```

```{r}
#temperature extraction function
tmp_extract_data <- function(datetime, url){
  dt_char <- as.character(datetime)
  tmp_url <- paste0(url, "?date_time=", 
             substr(dt_char, 1, 10), "T", 
             substr(dt_char, 12, 19))

  tmp_data <- RcppSimdJson::fparse(GET(tmp_url)$content)
  tmp_st <- tmp_data$metadata$stations
  tmp_st$latitude <- sapply(tmp_st$location, `[[`, 1)
  tmp_st$longtitude <- sapply(tmp_st$location, `[[`, 2)
  tmp_st <- tmp_st %>% select(c(-location, -device_id))
  tmp_rd <- tmp_data$items$readings[[1]]
  colnames(tmp_rd)[2] <- 'temperature'
  tmp_final <- merge(tmp_st, tmp_rd, by.x = "id", by.y = "station_id")
  tmp_final$datetime <- rep(datetime, nrow(tmp_final))
  return(setDT(tmp_final))
}
```

```{r}
#function to retrieve and clean api data for carpark availability data
cp_extract_data <- function(datetime, url){
  datetime_char <- as.character(datetime)
  url <- paste0(url, "?date_time=", 
                substr(datetime_char, 1, 10), "T", 
                substr(datetime_char, 12, 19))
  
  data <- RcppSimdJson::fparse(GET(url)$content)
  
  carpark <- setDT(data$items$carpark_data[[1]][,2:3])
  carpark_info <- setDT(data$items$carpark_data[[1]][,1])
  
  carpark$update_datetime <- rep(datetime, length(carpark[[1]]))
  carpark$total_lots <- sapply(carpark_info, `[[`, 1)
  carpark$lot_type <- sapply(carpark_info, `[[`, 2)
  carpark$lots_available <- sapply(carpark_info, `[[`, 3)
  
  carpark <- carpark %>% 
    unnest(cols = c(total_lots, lot_type, lots_available))
  
  setDT(carpark)
  
  carpark[, c("total_lots", "lots_available") := lapply(.SD, as.numeric), .SDcols = c("total_lots", "lots_available")]
  
  return(carpark)
}
```

```{r}
dm_carpark_extract <- function(shift, url){
  url <- paste0(url, "&$skip=", as.character(shift))
  
  api_headers <- add_headers(
    AccountKey = 'HD1y2lhTRXaJIo9Q4hn/ow==',
    accept = 'application/json')
  
  res <- GET(url = url,
             config = api_headers)
  res_txt <- rawToChar(res$content)
  carpark <- RcppSimdJson::fparse(res_txt)$value
  carpark <- setDT(carpark)
  carpark[, c('Latitude', 'Longtitude') := tstrsplit(Location, " ")]
  carpark[, c('Latitude', 'Longtitude') := lapply(.SD, as.numeric), .SDcols = c('Latitude', 'Longtitude')]
  carpark[, c('Location', 'Development', 'Area') := NULL]
  
  return(carpark)
}

dm_carpark_extract_data <- function(datetime, url){
  datetime_char <- as.character(datetime)
  url <-  paste0(url, "?date_time=", 
                substr(datetime_char, 1, 10), "T", 
                substr(datetime_char, 12, 19))
  v <- 0:5 * 500
  data <- rbindlist(lapply(v, dm_carpark_extract, url))
  data[, datetime := datetime]
  return(data)
}
```

```{r}

# test_dataset_dm <- dm_carpark_extract_data(test_date, dm_carpark_url)
# dm_unique_carpark <- unique(test_dataset_dm$CarParkID)
# datagov_carpark_df <- setDT(read.csv("../Data Files/carpark_data_resultsfivepercent.csv"))
# range(datagov_carpark_df$update_datetime)
# datagov_unique_carpark <- unique(datagov_carpark_df$carpark_number)
# test <- unique_carpark[!datagov_unique_carpark %in% dm_unique_carpark]
# 
# datagov_carpark_df[, c('update_datetime', 'lot_type', 'lots_available', 'X') := NULL]
# total_lots <- unique(datagov_carpark_df, by = 'carpark_number')
# 
# 
# print(test)

```


```{r}
retry_function <- function(func, ..., max_attempts = 3, attempt = 1, check_empty = TRUE) {
  # Try running the function safely
  result <- purrr::safely(func)(...)
  
  # Check if the result is valid (no error, and non-empty output if specified)
  if (is.null(result$error) && (!check_empty || (!is.null(result$result) && length(result$result) > 0))) {
    return(result$result)  # Return the valid result
  }
  
  # If max attempts reached, return NULL
  if (attempt >= max_attempts) {
    return(list(...)[[1]])  # Return NULL if all attempts fail
  }
  
  # Tail-recursive call, efficient even with many iterations
  Recall(func, ..., max_attempts = max_attempts, attempt = attempt + 1, check_empty = check_empty)

}
```

```{r}
#
carpark_historic_data_get <- function(datetime_seq){
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(cp_extract_data, .x, hdb_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}


#
temperature_historic_data_get <- function(datetime_seq){
  tmp_url = "https://api.data.gov.sg/v1/environment/air-temperature"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(tmp_extract_data, .x, tmp_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}

#
rainfall_historic_data_get <- function(datetime_seq){
  rf_url = "https://api-open.data.gov.sg/v2/real-time/api/rainfall"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(rf_extract_data, .x, rf_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}

#
humidity_historic_data_get <- function(datetime_seq){
  humid_url = "https://api.data.gov.sg/v1/environment/relative-humidity"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(humidity_extract_data, .x, humid_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}

#
windspeed_historic_data_get <- function(datetime_seq){
  ws_url = "https://api.data.gov.sg/v1/environment/wind-speed"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(wind_extract_data, .x, ws_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}

dm_carpark_historic_data_get <- function(datetime_seq){
  dm_carpark_url <- "https://datamall2.mytransport.sg/ltaodataservice/CarParkAvailabilityv2"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(dm_carpark_extract_data, .x, dm_carpark_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}

rainfall2_historic_data_get <- function(datetime_seq){
  rf2_url <- "https://api.data.gov.sg/v1/environment/rainfall"
  data <- furrr::future_map(datetime_seq, 
                            ~ retry_function(get_rainfall_data_hour, .x, rf2_url), 
                            .progress = T, .options = furrr_options(seed = T))
  bool <- sapply(data, is.data.frame)
  res <- rbindlist(data[bool])
  error_dates <- rbind(data[!bool])
  return(list(results = res, error = error_dates))
}
```

```{r}
query_date_seq <- seq(as.POSIXct("2023-01-01 00:01:00"),
                      as.POSIXct("2024-01-01 00:01:00"),
                      by = "hour")

carpark_info_dataset <- rbindlist(lapply(offset_url, retrieve_carpark_info))
carpark_data <- carpark_historic_data_get(query_date_seq)
temperature_data <- temperature_historic_data_get(query_date_seq)
rainfall_data <- rainfall_historic_data_get(query_date_seq)
humidity_data <- humidity_historic_data_get(query_date_seq)
windspeed_data <- windspeed_historic_data_get(query_date_seq)
dm_carpark_data <- dm_carpark_historic_data_get(query_date_seq)
rainfall2_data <- rainfall2_historic_data_get(query_date_seq)
range(rainfall2_data$results$value)
```

```{r}
write.csv(rainfall2_data$results, "/Users/Xinyu/Desktop/Study Materials/Year 4/Sem 1/DBA3702/Project/Data Files/rainfall_data.csv")
```